### PR TITLE
Rebased Smoltcp example

### PR DESCRIPTION
**Pull request by podhrmic**
Supersedes https://github.com/GaloisInc/rust-seL4-sel4cp-demo/pull/8

### CODE REVIEW

**Comment by podhrmic** [comment]
@protoben I found out that `test_ethernet_loopback` can be called at most `TX/RX_BUF_SIZE` so something is not clearing the buffer slots properly.

**Comment by podhrmic** [comment]
For the UDP test, it was just getting stuck in an infinite loop - I modified the `loop` with a match, and this is the result:
```
banscii> Got notification!
Testing UDP loopback
Bound UDP socket 127.0.0.1:9001
Sent a UDP packet to 127.0.0.1:9001: PING
Error:Exhausted
Error:Exhausted
Got a UDP packet from 127.0.0.1:9001: PING
...
# any future round:
Error:Exhausted
...
```

**Comment by podhrmic** [comment]
I added some other small changes, such as a simulated system clock - now I can receive the UDP packet two times before all the buffers are exhausted.

**Comment by podhrmic** [comment]
I suspect that there is some logic error in the `EthInterface` or some buffers are not being cleared properly.

**Comment by protoben** [comment]
For posterity: The problem mentioned above stemmed from not handling the case where the client failed to use a `TxToken`. Making `TxToken` implement `Drop` by putting the buffer descriptor back in the free ring fixed the issue.

**Pull request merged**
